kind: Deployment
apiVersion: apps/v1
metadata:
  # 部署名称
  name: vue-sample-dev
  # 名称空间
  namespace: ks-vue-sample-dev
  labels:
    app: vue-sample-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-sample-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vue-sample-dev
    spec:
      containers:
        # 容器名称
        - name: vue-sample-dev
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  # 服务名
  name: vue-sample-dev
  # 名称空间
  namespace: ks-vue-sample-dev
  labels:
    app: vue-sample-dev
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      # 容器端口
      targetPort: 80
      # 节点端口, 供外部访问, 不能一样
      # 默认范围: 30000 - 32767
      # nodePort: 32001
  selector:
    # 和deployment一致
    app: vue-sample-dev
  type: NodePort
  sessionAffinity: None
